export const BUTTON_CLICKED_REQUEST = 'BUTTON_CLICKED_REQUEST';
export const BUTTON_CLICKED_SUCCESS = 'BUTTON_CLICKED_SUCCESS';
export const BUTTON_CLICKED_FAIL = 'BUTTON_CLICKED_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const PERSIST_REHYDRATE = 'persist/REHYDRATE';
